# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Syllable' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Syllable
  pod "TinyConstraints"
  pod 'IQKeyboardManagerSwift'
  pod 'SKCountryPicker'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'AppCenter'

end
